- packages/react-native-views/src/components/TutorialView/index.jsx
- packages/react-native/src/components/PicturesScrollPreview/styles.js
Fixed getting started button overlaps the advice modal.
Couldn't find the crop error of the advice modal.
> Feature/fe 223/intergration issues in advices

- packages/corejs/src/users/usersApi.js
There is an error whenever the user loads the profile page. I think it comes from the fact that if the user does not have a signature yet, then the api send a json response like that:
```json
{
"has_signature": false
}
```
But at first I did not checked that and take the response as a Blob without taking in consideration that the response could be a json even if the param query `return_image` was at `true`.
The problem now is that I don't know how to handle the case where it fails, so I temporarily put a `Promise.reject()`.
> Fix Get Signature format error

- packages/react-native/src/components/DamageHighlight/index.js
Manual damage image not displaying in DamageRead screen
Changes on the DamageHighlight component
- Web
- Emulator iOS 11
> Fix manual damage image not displaying

- packages/react-native-views/src/components/CreateDamageForm/DamageRow/index.js
- packages/react-native-views/src/components/CreateDamageForm/useDamagesForm.js
Fixed form row part_type and damage_type value (was getting overflow) on android and small screens.
- Android pixel 4 XL
- Web browser
1. Open the create damage form on Android
2. Choose a long value of Damage Type or Part Type
Before
After
> Fixed the damage form row trim bug(on android)

- packages/react-native-views/src/components/CreateDamageForm/DamageForm/index.js
- packages/react-native-views/src/components/CreateDamageForm/DamageRow/index.js
- packages/react-native-views/src/components/CreateDamageForm/index.js
- packages/react-native-views/src/components/CreateDamageForm/useDamagesForm.js
- packages/react-native-views/src/components/Drawer/index.js
- packages/react-native-views/src/components/Select/index.js
Created a new select component based on react-native-paper Menu.
Implemented on the DamageForm.
Fixed the drawer layout to avoid a flickering UI.
This PR is related to [Directly use picker on the Damage Create form](https://monkvision.atlassian.net/browse/FE-254)
- iOS iPhone 8
- Android pixel 4 xl
- Chrome browser
1. Add part_type and damage_type inside the damage library
> Feature/fe 254/new select component

- src/App.js
- src/config/ignoreLogs.js
Sometimes we get some console errors/warnings that we can't fix as they are coming from a package somehow, e,g **react-navigation** or **react-native-paper** are throwing `EventEmitter.addListener`.
Added a function config which will remove all the given errors/warnings as param, from the console one web, and will remove the also the annoying ones from the native `LogBox`.
> Get rid of the annoying useless warnings

- packages/camera/src/components/Capture/hooks.js
Fixed `onCaptureTourFinish` capture prop getting called two times, basically we don't need it on line 157 because we are calling it bellow after the upload finish (in both cases fulfilled and rejected).
See line 207 and 220.
This PR is related to Capture component.
- Web chrome
1. Pass a callback to onCaptureTourFinish
> Fixed onCaptureTourFinish getting called 2 times

- package.json
- tsconfig.json
- yarn.lock
Fixes a bug that prevents the installation of the packages because typescript (and some type defs packages) were not installed locally in the workspace root.
> fix: Package installation fails due to typescript missing locally

- packages/camera/src/components/Capture/hooks.js
- iPhone 8/chrome
- M1 air/chrome
1. Take pictures
2. Check the logs or see them on sentry
> Added logs when taking a picture

- packages/camera/src/components/Capture/capture.js
- Mac Air m1/chrome
1. On cra apps Capture view should fit the whole screen (no empty margins)
> Fixed the capture layout issue

- packages/camera/src/components/UploadCenter/button.js
- packages/camera/src/components/UploadCenter/index.js
- Mac air/M1 chrome
1. Try add a prop `navigationOptions={{ allowSkip: false }}`, to the capture component.
2. Take the capture tour, when you land on the upload center, the Skip button should be disabled.
> Implemented the allowSkip navigationOption on uploadcenter

- src/screens/InspectionCapture/settings.js
- src/screens/InspectionCapture/styles.js
- Mac air m1/chrome
1. Open the camera
2. Open the settings
3. Hit fullscreen
> Added fullscreen toggle, without toggle off

- packages/camera/src/components/Capture/hooks.js
- packages/camera/src/components/UploadCenter/UploadCard/hooks/useStatus.js
- packages/camera/src/components/UploadCenter/UploadCard/hooks/useVariant.js
- packages/camera/src/components/UploadCenter/UploadCard/index.js
- packages/camera/src/components/UploadCenter/hooks/useComplianceIds.js
- Mac air chrome
1. It is very rare when we get a null compliance, but in order to test just take the tour
2. On the upload center the flow shouldn't be stuck in the queue (at least on of the compliances should .
> Fixed when an image get a null compliance and blocks the all the queue

- src/screens/InspectionCapture/settings.js
- Mac Web chrome
- iphone 8 chrome
1. Open the settings
2. Should be open
> Fixed a typo that was preventing the modal from being opened

- src/screens/InspectionCapture/settings.js
- Mac m1 chrome
1. Open the camera settings menu
2. Rotate to portrait
3. Expected: the menu should be closed 
> Return null if the rotation is portrait

- packages/visualization/package.json
- packages/visualization/src/components/DamageAnnotations/index.js
- packages/visualization/src/components/DamageHighlight/index.js
- packages/visualization/src/components/ElementHighlight/index.js
- services/inspection-report/src/views/InspectionDetails/ImageList/index.js
- services/inspection-report/src/views/InspectionDetails/index.js
- services/inspection-report/src/views/InspectionDetails/useGetInspection/index.js
- services/inspection-report/src/views/Inspections/index.js
- website/docs/js/api/components/DamageAnnotation.md
- website/docs/js/api/components/DamageHighlight.md
* Modifications on the DamageHighlight component : 
* Creation of ElementHighlight for a generalization of the component to create other component (for instance PartHighlight)
* Remove damage labels, because if there are too much damages, it can quickly become unreadable
* Modification of the props of DamageHighlight for an easier use of the component by putting inspection's image and damages
* Manual damages are represent by ellipses and AI detected damages by an ellipse
* Fix some warning messages about click/press event
* Modifications on the DamageAnnotation component :
* Add `Reset` and `CreateDamageView` ref functions to add a damage on a an already uploaded image or on a new image to upload
* Update documentation
* Fix on Inspection report app, the `get inspections` request error
- …
> Enhancement Damage highlight refacto

- app.config.js
- src/components/Inspection/index.js
- src/i18n/resources/en.js
- src/i18n/resources/fr.js
- src/screens/InspectionCapture/index.js
- src/screens/Landing/LanguageSwitch/index.js
- src/screens/Landing/index.js
- src/screens/Landing/useGetPdfReport/index.js
#MN-108 : Moved the photo section to the bottom of the page
#MN-109 : Added some missing translations and fixed the bug where the selected language at startup would not be correct
#MN-110 : Integrated the Wheels Analysis workflow into the Damage Detection workflow.
#MN-111 : Moved the download PDF button to a new row and created a new section for it.
#MN-115 : Made it so the generated PDF is in the same language as the app.
> feat: Last Webapp enhancements before shipping

- packages/camera/src/components/UploadCenter/UploadCard/hooks/useVariant.js
- packages/camera/src/i18n/resources/en.js
- packages/camera/src/i18n/resources/fr.js
Replace the functionality of "Reupload Picture" with "Retake Picture"
- When the picture was not uploaded correctly, KEEP the thumbnail color in red
- When the picture was not uploaded correctly, instead of displaying “reupload picture” we want to display “retake picture”
- When the picture was not uploaded correctly and the user clicks on the thumbnail, instead of trying to reupload the picture, we want to retake the picture (we want to have the same behaviour as for the not compliant images)
-
- 
1. 
2. 
> retake the picture instead of reuploading the picture

- packages/camera/src/components/Camera/hooks/useCamera.js
- packages/camera/src/components/Capture/capture.js
- packages/camera/src/components/Capture/hooks.js
- packages/camera/src/components/Controls/hooks.js
1. Allow the user to capture the image for next sight without waiting for the whole operation completion on previous sight's picture.
2. Allow the user to move to next sight after 1/2 second only and then user can click on the capture button to trigger the call to capture the image.
3. The line up operations on the picture will be executed in background like creating a blob from Canvas element and get URI, generating a thumbnail, and uploading the image with given task_name etc.
4. Once every picture status will be updated to either 'rejected' or 'fulfilled' then user will be taken to "Upload Centre".
5. Handling failure scenario for each operation for instance <thumbnail creation>
> Improve Capture UX

- packages/camera/src/components/Camera/hooks/useCamera.js
Made a few modification to optimise HTML 5 canvas specially for following things:
1. Using `alpha=false` while drawing an image into canvas 2d context from video
2. Using `toDataURL` method directly on canvas instead of creating a Blob object from canvas and then get URI
> made a few minor changes to optimize HTML5 canvas for Android device

- packages/corejs/src/monitoring/index.tsx
A very tiny PR about setting some default value to Sentry config during the initialisation
> set some default value to Sentry config during the initialization

- packages/camera/src/components/Capture/capture.js
- src/screens/InspectionCapture/index.js
1.  Modify SDK for Sentry code to make sentry configuration & setup easy and minimal in client apps
2. Move sentry transaction code from `InspectionCapture` component (in client app) to `Capture` component (in SDK) to track whole capture tour
3. Change the quit button with `Controls.CloseEarlyButtonProps` in place of `Controls. GoBackButtonProps` to handle the tour cancel and sentry transaction call respectively  in `Capture` component
> Modify SDK with Sentry code to make Sentry config easy and minimal in client app

- packages/corejs/src/monitoring/index.tsx
- packages/corejs/src/monitoring/types.ts
- website/docs/monitoring.md
Allow users to add custom tags at the time of initializing sentry. These custom tags will always be set in all the transactions.
> feat: allow user to add custom tags (MN-274)

- src/config/Navigation.js
- src/contexts/clients/workflows/index.js
- src/contexts/clients/workflows/workflows.js
- src/screens/CaptureVehicleSelection/index.js
- src/screens/CaptureVehicleSelection/styles.js
- src/screens/Landing/index.js
- src/screens/index.js
- src/screens/names.js
- src/screens/paramsMap.js
Added new workflow CAPTURE_VEHICLE_SELECTION for CAT application.
If vehicle type is not provided for CAT, then the user will be redirected to the vehicle type selection screen, else will redirect to the capture screen.
> feat: create vehicle type selection (MN-297)

- packages/inspection-report/src/components/CarView360/index.js
- packages/inspection-report/src/components/DamageReport/DamageManipulator.js
- packages/inspection-report/src/components/DamageReport/DamageReport.js
- packages/inspection-report/src/components/DamageReport/Overview/index.js
- packages/inspection-report/src/components/DamageReport/UpdateDamageModal.js
- packages/inspection-report/src/components/DamageReport/UpdateDamagePopUp/index.js
- packages/inspection-report/src/components/DamageReport/hooks/usePdfReport.js
- packages/inspection-report/src/hooks/index.js
- packages/inspection-report/src/hooks/useOrientation.js
- src/screens/Authentication/SignIn/index.js
* In `src/components/DamageReport/hooks/usePdfReport.js` line 48, switch to `pricing: true` in the PDF payload
* Set the pricing slider limit to 1500
* In `src/Screens/Authentication/SignIn/index.js` change the color of the success button from `colors.success` to `colors.primary` and verify that it is blue
* Replace the content of the download report button (the button with the damageReport.download label in `Overview/index.js` with a loader while it is loading (any basic loader will suffice)
* Remove the back-button at the top-left of the screen (in the header)
* Add a padding bottom at the end of the DamageManipulator so that the user can scroll down to the “done” button when the screen is too small (as you can see in the screenshot below). Only add the padding bottom if the screen is …
> Make the changes as per QA feedback

- packages/inspection-report/src/components/DamageReport/DamageReport.js
- packages/inspection-report/src/components/DamageReport/hooks/usePdfReport.js
- packages/inspection-report/src/i18n/resources/en.js
- packages/inspection-report/src/i18n/resources/fr.js
Reset pdf status to not started if we have any error on generating pdf
> fix: reset pdf generate api call on error (MN-327)

- src/screens/InspectionCapture/index.js
- src/screens/Landing/index.js
> fix an issue to show the VIN capture sight in capture-tour when user selects VIN task from landing page

- packages/inspection-report/src/assets/IconSeverityMedium.js
- packages/inspection-report/src/components/CarView360/hooks/useInnerHTML.js
- packages/inspection-report/src/components/DamageReport/DamageManipulator.js
- packages/inspection-report/src/components/DamageReport/DamageReport.js
> MN-333 - Fix to display moderate symbol correctly in iOS

- apps/monk-test-app/src/views/TestView/TestView.css
- apps/monk-test-app/src/views/TestView/TestView.tsx
- packages/public/camera-web/README.md
- packages/public/camera-web/src/Camera/Camera.tsx
- packages/public/camera-web/src/Camera/hooks/useCameraCanvas.ts
- packages/public/camera-web/src/Camera/hooks/utils/getMediaContraints.ts
- packages/public/camera-web/test/Camera/Camera.test.tsx
- packages/public/camera-web/test/Camera/hooks/useCameraCanvas.test.ts
- packages/public/camera-web/test/Camera/hooks/utils/getMediaConstraints.test.ts
- packages/public/common/src/utils/array.utils.ts
- packages/public/common/test/utils/promise.utils.test.ts
The goal of this PR is to implement a feature where the Camera preview is always displayed using the highest resolution possible. We then manually scale the screenshot to fit the required constraints for the resolution.
> Always display camera preview with highest res possible

- apps/demo-app/src/index.css
- packages/inspection-capture-web/src/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUDButtons/PhotoCaptureHUDButtons.styles.ts
- packages/inspection-capture-web/src/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUDButtons/hooks.ts
- packages/inspection-capture-web/src/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUDPreviewAddDamage1stShot/PhotoCaptureHUDPreviewAddDamage1stShot.styles.ts
- packages/inspection-capture-web/src/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUDPreviewAddDamage1stShot/PhotoCaptureHUDPreviewAddDamage1stShot.tsx
- packages/inspection-capture-web/src/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUDPreviewAddDamage1stShot/hook.ts
- packages/inspection-capture-web/src/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUDPreviewAddDamage2ndShot/PhotoCaptureHUDPreviewAddDamage2ndShot.styles.ts
- packages/inspection-capture-web/src/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUDPreviewAddDamage2ndShot/PhotoCaptureHUDPreviewAddDamage2ndShot.tsx
- packages/inspection-capture-web/src/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUDPreviewAddDamage2ndShot/hook.ts
- packages/inspection-capture-web/src/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUDPreviewSight/PhotoCaptureHUDPreviewSight.styles.ts
- packages/inspection-capture-web/src/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUDPreviewSight/PhotoCaptureHUDPreviewSight.tsx
- packages/inspection-capture-web/src/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUDPreviewSight/SightsSlider/SightsSlider.styles.ts
- packages/inspection-capture-web/src/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUDPreviewSight/SightsSlider/SightsSlider.tsx
- packages/inspection-capture-web/src/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUDPreviewSight/SightsSlider/hook.ts
- packages/inspection-capture-web/src/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUDPreviewSight/hook.ts
- packages/inspection-capture-web/test/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUDPreviewAddDamage2ndShot.test.tsx
Fixed PhotoCapture top part cropped in portrait orientation.
- Self-QA was made on both desktop and mobile
> Fixed PhotoCapture top part cropped in portrait orientation

- apps/drive-app/src/pages/PhotoCapturePage/PhotoCapturePage.tsx
- packages/inspection-capture-web/src/PhotoCapture/PhotoCapture.tsx
- packages/inspection-capture-web/src/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUD.tsx
- packages/inspection-capture-web/src/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUDPreview/PhotoCaptureHUDPreview.tsx
- packages/inspection-capture-web/src/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUDPreviewSight/AddDamageButton/AddDamageButton.tsx
- packages/inspection-capture-web/src/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUDPreviewSight/PhotoCaptureHUDPreviewSight.tsx
- packages/inspection-capture-web/src/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUDPreviewSight/SightSlider/SightSlider.styles.ts
- packages/inspection-capture-web/test/PhotoCapture/PhotoCapture.test.tsx
- packages/inspection-capture-web/test/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUDPreviewSight/AddDamageButton.test.tsx
Jira Ticket Reference : [MN-517](https://acvauctions.atlassian.net/browse/MN-517)
Allows developer to disable the `Add Damage` feature and button. 
[MN-517]: https://acvauctions.atlassian.net/browse/MN-517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Disable option for AddDamage feature

- packages/inspection-capture-web/src/PhotoCapture/PhotoCapture.tsx
- packages/inspection-capture-web/src/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUD.tsx
- packages/inspection-capture-web/src/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUDPreview/PhotoCaptureHUDPreview.tsx
- packages/inspection-capture-web/src/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUDPreviewSight/PhotoCaptureHUDPreviewSight.tsx
- packages/inspection-capture-web/src/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUDPreviewSight/SightSlider/SightSlider.tsx
- packages/inspection-capture-web/test/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUD.test.tsx
- packages/inspection-capture-web/test/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUDPreview.test.tsx
- packages/inspection-capture-web/test/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUDPreviewSight/SightSlider/SightSlider.test.tsx
Jira Ticket Reference : [MN-520](https://acvauctions.atlassian.net/browse/MN-520)
Fix onRetakeSIght callback for non compliant sight instead of onSelectedSight.
[MN-520]: https://acvauctions.atlassian.net/browse/MN-520?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix retake non compliant Sight slider

- packages/common-ui-web/src/components/ImageDetailedView/ImageDetailedViewOverlay/ImageDetailedViewOverlay.tsx
- packages/common-ui-web/src/components/ImageDetailedView/ImageDetailedViewOverlay/hooks.ts
- packages/common-ui-web/src/components/InspectionGallery/InspectionGallery.tsx
- packages/common-ui-web/src/components/InspectionGallery/hooks/useInspectionGalleryItems.ts
- packages/common-ui-web/test/components/ImageDetailedView/ImageDetailedViewOverlay/ImageDetailedViewOverlay.test.tsx
- packages/common-ui-web/test/components/ImageDetailedView/ImageDetailedViewOverlay/hooks.test.ts
- packages/common-ui-web/test/components/InspectionGallery/hooks/useInspectionGalleryItems.test.ts
- packages/common/src/i18n/translations/image.ts
- packages/common/src/state/actions/createdOneImage.ts
- packages/common/src/state/actions/gotOneInspection.ts
- packages/common/src/state/actions/updatedManyTasks.ts
- packages/common/src/utils/state.utils.ts
- packages/common/test/utils/state.utils.test.ts
- packages/inspection-capture-web/src/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUDPreviewSight/SightSlider/SightSlider.tsx
- packages/inspection-capture-web/src/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUDPreviewSight/SightSlider/SightSliderButton.tsx
- packages/inspection-capture-web/src/PhotoCapture/hooks/usePhotoCaptureSightState.ts
- packages/inspection-capture-web/test/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUD.test.tsx
- packages/inspection-capture-web/test/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUDPreview.test.tsx
- packages/inspection-capture-web/test/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUDPreviewSight/PhotoCaptureHUDPreviewSight.test.tsx
- packages/inspection-capture-web/test/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUDPreviewSight/SightSlider/SightSlider.test.tsx
- packages/inspection-capture-web/test/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUDPreviewSight/SightSlider/SightSliderButton.test.tsx
- packages/inspection-capture-web/test/PhotoCapture/hooks/usePhotoCaptureImages.test.ts
- packages/inspection-capture-web/test/PhotoCapture/hooks/usePhotoCaptureSightState.test.ts
- packages/network/src/api/image/mappers.ts
- packages/network/src/api/image/requests.ts
- packages/network/src/api/models/image.ts
- packages/network/test/api/image/mappers.test.ts
- packages/network/test/api/inspection/data/apiInspectionGet.data.json
- packages/network/test/api/inspection/data/apiInspectionGet.data.ts
- packages/types/src/state/image.ts
Jira Ticket Reference : [MN-524](https://acvauctions.atlassian.net/browse/MN-524)
- Fix compliance statuses not updating on refresh in SightSlider and ComplianceBadge
- Allow retake of compliant sights
- Fix refresh when every picture has been taken
- Added `sightId` and `createdAt` properties in `Image` interface to avoid having to deal with additional data everywhere
[MN-524]: https://acvauctions.atlassian.net/browse/MN-524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix Refresh in PhotoCapture

- apps/demo-app/.env-cmdrc.json
- apps/demo-app/package.json
- apps/drive-app/.env-cmdrc.json
- apps/drive-app/package.json
- packages/camera-web/README.md
- packages/camera-web/src/Camera/Camera.tsx
- packages/camera-web/src/Camera/CameraHUD.types.ts
- packages/camera-web/src/Camera/hooks/useCameraPreview.ts
- packages/camera-web/test/Camera/hooks/useCameraPreview.test.tsx
- packages/inspection-capture-web/src/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUD.tsx
- packages/inspection-capture-web/src/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUDElements/PhotoCaptureHUDElements.tsx
- packages/inspection-capture-web/src/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUDElementsSight/PhotoCaptureHUDElementsSight.tsx
- packages/inspection-capture-web/src/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUDElementsSight/hooks.ts
- packages/inspection-capture-web/test/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUD.test.tsx
- packages/inspection-capture-web/test/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUDElements.test.tsx
- packages/inspection-capture-web/test/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUDElementsSight/PhotoCaptureHUDElementsSight.test.tsx
Jira Ticket Reference : [MN-522](https://acvauctions.atlassian.net/browse/MN-522)
This PR fixes an issue causing the sight overlays to sometimes go out of the camera stream bounds. This issue was caused by the fact that the `aspectRatio` property (used to properly size the sight overlay compared to the camera stream) is bugged in Safari and doesn't work as expected. To fix this, I added a function that automatically calculates the effective size of the camera preview on the stream in pixels, added these dimensions to the camera handle, and used them in the PhotoCapture component to properly size the sight overlay without having to use `aspectRatio`.
- **Self-QA was made on both desktop and …
> Fixed the aspect ratio of the sights

- packages/common-ui-web/src/components/ImageDetailedView/ImageDetailedViewOverlay/ImageDetailedViewOverlay.styles.ts
- packages/common-ui-web/src/components/ImageDetailedView/ImageDetailedViewOverlay/hooks.ts
Jira Ticket Reference : [MN-544](https://acvauctions.atlassian.net/browse/MN-544)
Fixed background gradient not displaying in gallery image overlay
[MN-544]: https://acvauctions.atlassian.net/browse/MN-544?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fixed background gradient not displaying in gallery image overlay

- documentation/src/components/Sights/LabelTable/LabelTable.tsx
Jira Ticket Reference : [MN-555](https://acvauctions.atlassian.net/browse/MN-555)
dutch language column is missing in global doc's Sights lable
- The acceptance criteria listed in the ticket are met.
[MN-555]: https://acvauctions.atlassian.net/browse/MN-555?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> 🐛 nl translation missing

- documentation/src/components/Sights/SightCard/SightCard.tsx
- documentation/src/components/Sights/TopBar/TopBar.tsx
- documentation/src/pages/Sights/index.tsx
- packages/common-ui-web/src/components/DynamicSVG/DynamicSVG.tsx
- packages/common-ui-web/src/components/DynamicSVG/SVGElement.tsx
- packages/common-ui-web/src/components/DynamicSVG/hooks/types.ts
- packages/common-ui-web/src/components/DynamicSVG/hooks/useCustomAttributes.ts
- packages/common-ui-web/src/components/DynamicSVG/hooks/useJSXTransformAttributes.ts
- packages/common-ui-web/test/components/DynamicSVG/SVGElement.test.tsx
- packages/common-ui-web/test/components/DynamicSVG/hooks/useCustomAttributes.test.ts
- packages/common-ui-web/test/components/DynamicSVG/hooks/useInnerHTML.test.ts
Jira Ticket Reference : [MN-554](https://acvauctions.atlassian.net/browse/MN-554)
seems `getAttributes` is used to add styles it unintentionally overrides the style.
[MN-554]: https://acvauctions.atlassian.net/browse/MN-554?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> 🐛 svg styles override unintentionally

- configs/test-utils/src/__mocks__/@monkvision/network.ts
- packages/inspection-capture-web/src/PhotoCapture/hooks/useUploadQueue.ts
- packages/inspection-capture-web/test/PhotoCapture/hooks/useUploadQueue.test.ts
- packages/network/src/api/image/requests.ts
- packages/network/src/api/index.ts
- packages/network/src/api/inspection/mappers.ts
- packages/network/test/api/image/requests.test.ts
- packages/network/test/api/inspection/data/apiInspectionPost.data.json
- packages/network/test/api/inspection/data/apiInspectionPost.data.ts
- packages/types/src/api.ts
- packages/types/src/state/image.ts
- packages/types/src/state/vehicle.ts
Jira Ticket Reference : [MN-562](https://acvauctions.atlassian.net/browse/MN-562)
- Create network requests for the VideoCapture component
[MN-562]: https://acvauctions.atlassian.net/browse/MN-562?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Feat/mn 562/network video requests

- packages/camera-web/src/Camera/hooks/useUserMedia.ts
- packages/camera-web/src/utils/errors.utils.ts
- packages/camera-web/test/Camera/hooks/useUserMedia.test.ts
Jira Ticket Reference : [MN-584](https://acvauctions.atlassian.net/browse/MN-584)
[MN-584]: https://acvauctions.atlassian.net/browse/MN-584?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Feat/mn 584/specfic error message camera

- packages/common/src/apps/appStateProvider.tsx
- packages/common/src/apps/searchParams.ts
- packages/common/test/apps/appStateProvider.test.tsx
- packages/common/test/apps/searchParams.test.ts
Jira Ticket Reference : [MN-615](https://acvauctions.atlassian.net/browse/MN-615)
The MonkAppStateProvider now only allows vehicle types present in the app config to be fetched in the URL
[MN-615]: https://acvauctions.atlassian.net/browse/MN-615?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Use only the vehicle types in the app config when fetching from the URL

- packages/common/src/hooks/useObjectTranslation.ts
- packages/common/test/hooks/useObjectTranslation.test.ts
Jira Ticket Reference : [MN-616](https://acvauctions.atlassian.net/browse/MN-616)
Allowed useObjectTranslation to accept the same params as useTranslation
[MN-616]: https://acvauctions.atlassian.net/browse/MN-616?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Allowed useObjectTranslation to accept the same params as useTranslation

- packages/network/src/api/inspection/mappers.ts
- packages/network/src/api/models/vehicle.ts
- packages/network/test/api/inspection/data/apiInspectionPost.data.json
- packages/network/test/api/inspection/data/apiInspectionPost.data.ts
- packages/types/src/state/vehicle.ts
Jira Ticket Reference : [MN-628(https://acvauctions.atlassian.net/browse/MN-628)
Added serie field to the vehicle interface
> Added serie field to the vehicle interface

- documentation/src/utils/schemas.ts
- packages/network/src/api/inspection/mappers.ts
- packages/network/src/api/models/inspection.ts
- packages/network/src/api/models/task.ts
- packages/network/test/api/inspection/data/apiInspectionPost.data.json
- packages/network/test/api/inspection/data/apiInspectionPost.data.ts
- packages/types/src/api.ts
Jira Ticket Reference : [MN-648](https://acvauctions.atlassian.net/browse/MN-648)
Enable pricing via tasks.
[MN-648]: https://acvauctions.atlassian.net/browse/MN-648?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Enable pricing via tasks

- packages/network/src/api/inspection/mappers.ts
- packages/network/src/api/models/inspection.ts
Fixed api mapping sort options
> Fixed api mapping sort options

- packages/common-ui-web/src/components/CreateInspection/CreateInspection.tsx
Jira Ticket Reference : [MN-656(https://acvauctions.atlassian.net/browse/MN-656)
Fixed memory leak in CreateInspection component
> Fixed memory leak in CreateInspection component

- packages/network/src/api/inspection/mappers.ts
- packages/network/src/api/inspection/requests.ts
- packages/network/test/api/inspection/mappers.test.ts
- packages/network/test/api/inspection/requests.test.ts
Jira Ticket Reference : [MN-663](https://acvauctions.atlassian.net/browse/MN-663)
Fixed verbose param passed in getAllInspectionsCount request
[MN-663]: https://acvauctions.atlassian.net/browse/MN-663?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fixed verbose param passed in getAllInspectionsCount request

- packages/common/src/state/actions/gotOneInspectionPdf.ts
- packages/common/src/state/actions/index.ts
- packages/common/src/state/actions/monkAction.ts
- packages/common/src/state/reducer.ts
- packages/common/test/state/actions/gotOneInspectionPdf.test.ts
- packages/common/test/state/reducer.test.ts
- packages/network/README.md
- packages/network/src/api/api.ts
- packages/network/src/api/damage/requests.ts
- packages/network/src/api/error.ts
- packages/network/src/api/inspection/mappers.ts
- packages/network/src/api/models/pdf.ts
- packages/network/src/api/pdf/index.ts
- packages/network/src/api/pdf/requests.ts
- packages/network/src/api/react.ts
- packages/network/test/api/inspection/data/apiAllInspectionsVerboseGet.data.ts
- packages/network/test/api/pdf/requests.test.ts
Jira Ticket Reference : [MN-655](https://acvauctions.atlassian.net/browse/MN-655)
Added getPdf and uploadPdf functions
[MN-655]: https://acvauctions.atlassian.net/browse/MN-655?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Added upload PDF 

- packages/common/src/state/actions/createdOneDamage.ts
- packages/common/test/state/actions/createdOneDamage.test.ts
> Fixed createdOneDamage by filtering parts by inspectionId

- packages/inspection-capture-web/src/PhotoCapture/hooks/useInspectionComplete.ts
- packages/inspection-capture-web/test/PhotoCapture/hooks/usePhotoCaptureSightGuidelines.test.ts
Removed preventExit in photoCapture
> Removed preventExit in photoCapture

- packages/network/src/api/image/mappers.ts
- packages/network/src/api/image/requests.ts
- packages/network/src/api/inspection/mappers.ts
- packages/network/src/api/models/image.ts
- packages/network/src/api/models/task.ts
- packages/network/test/api/image/requests.test.ts
- packages/types/src/state/image.ts
- packages/types/src/state/task.ts
Jira Ticket Reference : [MN-700](https://acvauctions.atlassian.net/browse/MN-700)
Added `odometer` and `warning_lights` tasks to Network package.
[MN-700]: https://acvauctions.atlassian.net/browse/MN-700?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Added Odometer and Warning Lights tasks to network package

- packages/common-ui-web/src/components/CaptureSelection/translations/de.json
- packages/common-ui-web/src/components/CaptureSelection/translations/en.json
- packages/common-ui-web/src/components/CaptureSelection/translations/fr.json
- packages/common-ui-web/src/components/CaptureSelection/translations/nl.json
- packages/inspection-capture-web/src/translations/de.json
- packages/inspection-capture-web/src/translations/en.json
- packages/inspection-capture-web/src/translations/fr.json
- packages/inspection-capture-web/src/translations/nl.json
Jira Ticket Reference : [MN-710](https://acvauctions.atlassian.net/browse/MN-710)
[MN-710]: https://acvauctions.atlassian.net/browse/MN-710?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Changed bad connection and capture selection wording
