website/docs/js/guides/picturing.md
website/docs/js/guides/setting-up.md

Add docs for expo bare and managed workflows project

---

src/components/Pagination/index.jsx

Fixed issue [#118](https://github.com/monkvision/monkjs/issues/118).

Pagination workaround, styles polishing

---

.github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md

Trying to fix *our repo doesn't detect the pull request template*

Trying to fix template not getting populated by our repo

---

packages/corejs/src/index.js
packages/corejs/src/inspections/constants.js
packages/corejs/src/inspections/inspectionsSlice.js
src/screens/Landing/index.jsx

Added  two cards displaying 3 last **done** and **in progress** inspections with a status indicator, the list is similar to the one from the inspections screen:
- New Cell added for status
- Each card has it's own refresh button
- Subtitles will change depending on the length of the data.
This PR is related to [Improve Landing page](https://monkvision.atlassian.net/browse/FE-224)
Useful to make the user feel more engaged into our app.
- iOS (iPhone 13 pro)
- Android Pixel 3
- Web browser Chrome
1. Go to landing page
- Web:
- Mobile:

Feature/fe 224/improve landing page

---

packages/corejs/src/damages/damagesInsApi.js
packages/corejs/src/damages/damagesSlice.js
packages/corejs/src/index.js
packages/react-native-views/src/components/AdvicesView/index.jsx
src/components/ActionMenu/index.jsx
src/hooks/usePartDamages/index.js
src/hooks/useToggle/index.js
src/screens/DamageCreate/index.jsx
src/screens/DamageRead/CustomDialog/index.jsx
src/screens/DamageRead/index.jsx
src/screens/Damages/DamageListItem/index.jsx
src/screens/Damages/index.jsx
src/screens/Inspections/index.jsx

Draft PR
What is done
- Damage READ
- Damage DELETE <=> UPDATE
What is in Progress
- Damage CREATE

Feature/fe 219/manipulate damages

---

src/components/Img/index.jsx
src/components/Placeholder/index.jsx
src/hooks/useToggle/index.js
src/screens/InspectionRead/index.jsx
src/screens/Landing/index.jsx

---
name: 'New Pull Request '
about: 'Create new pull request'
title: "Title"
labels: Blog
assignees: ''
---
Added Img component which takes all Image props, The Img component has:
- A placeholder for image loading.
- An error card that appears when an error occurred while loading the image.
The component is fully animated.
And also I've added a status bar to the landing page.
This PR is related to [Add skeleton when images are loading on Inspection Read](https://monkvision.atlassian.net/browse/FE-229)
Useful to make the app look smooth, even if the user internet is slow...
- Chrome browser macOS
- iOS iPhone 8
- Android galaxy S7, Android pixel 2 
1. Go to …

Feature/fe 229/images skeleton

---

package.json
packages/corejs/src/index.js
packages/corejs/src/users/usersApi.js
packages/corejs/src/users/usersEntity.js
packages/corejs/src/users/usersSlice.js
src/Navigation.jsx
src/components/Signature/index.jsx
src/screens/Landing/index.jsx
src/screens/Profile/index.jsx
src/screens/index.js
src/screens/names.js
src/store/index.js
yarn.lock

* User information form
* User signature canvas and upload

[FE-215] User profile page

---

packages/react-native-views/src/components/DamagedPartsView/index.js
packages/react-native/src/components/Vehicle/index.jsx
src/screens/Damages/Scene/index.jsx
src/screens/Damages/index.jsx
yarn.lock

- Add selection stroke to highlight selected vehicle part, 
- navigate to create damage when inspection is not validated with the selected partType

select part from vehicle view and navigate to create damage

---

packages/react-native-views/src/components/CreateDamageForm/DamageForm/index.js
packages/react-native-views/src/components/CreateDamageForm/index.js
packages/react-native-views/src/components/Drawer/index.js
src/components/Drawer/index.js
src/screens/Damages/index.js
src/screens/Profile/EditSignatureForm/index.js

Fixed the drawer to be working on landscape orientation screens.
This PR is not related to any issue.
A drawer component should support all orientations.
- iPhone 8, 13 pro
- Android pixel 4 xl
- Chrome web browser, Chrome mobile 
1. Rotate your screen when you open the drawer

Fixed the drawer component to be working on landscape orientation

---

packages/react-native-views/src/components/CreateDamageForm/DamageForm/index.js
packages/react-native-views/src/components/CreateDamageForm/index.js

Added loading to the damage form submit button.
This PR is related to [Add a loader to the Add Damage button](https://monkvision.atlassian.net/browse/FE-253)
- Chrome web browser
1. Submit a damage manually

Added loading to damage form submit button

---

packages/react-native/src/components/DamageAnnotations/index.js
packages/react-native/src/components/DamageHighlight/index.js
packages/react-native/src/components/DamageImage/index.js
packages/react-native/src/hooks/useDamageImage/index.js

-
-
-
1. 
2. 
3. 
4. 
*This Pull Request template
has been written and generated by Monk JS repository.*

Fix damage highlight and annotation components

---

packages/react-native-views/src/components/Damages/index.js
packages/react-native-views/src/components/Thumbnail/ComplianceModal/index.js
packages/react-native-views/src/components/Thumbnail/index.js
packages/react-native-views/src/components/index.js
src/screens/InspectionImport/index.js

Created a new thumbnail component, with a modal explaining the compliance issue of the current image.
This PR is related to [New Thumbnail component](https://monkvision.atlassian.net/browse/FE-244)
No screenshots yet.

Feature/fe 244/new thumbnail component

---

src/screens/DamageRead/index.js

Added virtualization to read inspection pictures list
This PR is related to any issue.
- iOS
- Web Chrome
1. Open read inspection screen

Virtualization inside damage read

---

src/components/ImageViewer/index.js
src/hooks/useMediaGallery/index.js
src/screens/DamageRead/index.js
src/screens/InspectionRead/index.js

Display the right selected image in damage read
Fix the saved images name on web (Remove the extra = to the file name)
Q/A Fix inspection read picture previews selection
Q/A Fix save on device navigation and saved pictures name on the web

QA fix damage read image preview

---

packages/corejs/src/index.js
packages/corejs/src/users/usersApi.js
packages/corejs/src/users/usersSlice.js
src/screens/Profile/useSignature.js

-
-
-
1. Go to Account
2. Update user info and draw a signature
3. Submit
4. 

Fix signature file creation

---

src/screens/TaskRead/index.js

Added new button to start a task.
Cleanup for the old code.
This PR is not related to any issue.
- iOS
- Chrome web browser
1. Go to an inspection
2. Hit task ship

Add new button to start an inspection task, and a small code clean up

---

website/src/pages/Sights/SelectForm.js
website/src/pages/Sights/index.js
website/yarn.lock

Add category and vehicleType filter
-
-
-
1. 
2. 
3. 
4. 

Add search bar with autocompletion

---

src/screens/InspectionRead/index.js

.
Fixed app crashes when we delete the inspection from `inspectionRead` screen
- Chrome Web Browser
1. Delete inspection
2. You should be redirected to the inspections list 

Fixed app crash on delete inspection

---

app.config.js
packages/camera/src/components/Capture/hooks.js
packages/camera/src/components/Capture/index.js
packages/camera/src/utils/getWebFileDataAsync/index.js
src/screens/InspectionVin/VinForm/statuses.js
src/screens/InspectionVin/hooks/useVin.js
src/screens/InspectionVin/index.js

Implemented the new camera into the VIN screen.
This PR is related to VIN feature

Implement new camera into VIN

---

packages/corejs/src/inspections/index.js
packages/corejs/src/tests.js
website/docs/js/api/damages.md
website/docs/js/api/images.md
website/docs/js/api/inspections.md
website/docs/js/api/tasks.md
website/docs/js/api/views.md

Updated inspections docs, and implemented new code changes.
This PR is related to SDK v2

Sdk v2 inspections

---

packages/camera/package.json
packages/corejs/package.json
packages/cra-template/package.json
packages/cra-template/template/src/views/Inspector/index.jsx
packages/react-native-views/package.json
packages/react-native/package.json
packages/sights/package.json
packages/toolkit/package.json
packages/ui/package.json
packages/visualization/package.json

- Fixed camera `Capture` usage inside `cra-template`
- Added a full explanation for using UploadCenter
This PR is related to Camera capture.
- Chrome web browser
1. Finish the camera tour

Updated the usage of camera capture inside cra-template

---

packages/camera/src/components/Sights/index.js
packages/camera/src/components/Thumbnail/index.js

Added auto scroll whenever a sight got we focus in (Camera sights scrollView)
This PR is related to Capture.
- Web chrome

Scroll whenever a sight got focused

---

.github/workflows/webapp-deploy.yml
packages/corejs/src/config.js
packages/corejs/src/damages/damagesApi.js
packages/corejs/src/images/imagesApi.js
packages/corejs/src/inspections/inspectionsApi.js

That is a first version, that will be improved:
On a branch : can be deployed to https://webapp.dev.monk.ai -> call dev api (latest)
On main : will be deployed to https://webapp-staging.dev.monk.ai -> call staging api (stable)
On a tag : will be deployed to https://webapp.preview.monk.ai -> call preview api (stable)
It needs to create env: development/staging and preview with secrets
That was tested for webapp.dev and webapp-staging.dev

Automate webapp deploy

---

.github/workflows/webapp-deploy.yml

Fix: runners for webapp deploy

---

packages/camera/src/components/UploadCenter/index.js

Fixed upload center `zIndex` `0` to be `1`, all elements were not accessible.
This PR is related to Upload center
- Web chrome
- Ios Chrome

Fixed upload center actions not accessible

---

packages/cra-template/template/src/views/Inspector/index.jsx

Fixed a type error in cra-template

---

.github/workflows/webapp-deploy.yml

On some conditions, deploy can fail. This should improve things.

Fix deploy

---

.github/workflows/inspection-report.yml

Add deploy for inspection-report

---

.github/workflows/inspection-report.yml
.github/workflows/webapp-deploy.yml

comment workflow_dispatch

---

packages/camera/src/components/Controls/hooks.js

Fixed a bug of going to the next camera sight before uploading the prev image.
- Web chrome

Fixed passing to next sight before uploading

---

packages/camera/src/components/Layout/index.js
packages/camera/src/components/Thumbnail/index.js

Reference : https://monkvision.atlassian.net/browse/MN-71

fix: Sights labels cropped

---

packages/camera/src/components/Capture/capture.js
packages/camera/src/components/Capture/hooks.js
packages/camera/src/components/Controls/hooks.js
packages/camera/src/components/UploadCenter/hooks.js

-
-
-
1. Enable compliance on InspectionCapture
2. take photo
3. Expected to have all compliance reasons displayed on upload center
4. 

Wait compliances updates before going to upload center

---

.github/workflows/inspection-report.yml
.github/workflows/webapp-deploy.yml
Dockerfile
services/inspection-report/Dockerfile

In order to get a dedicated infra, this is a first step with a docker build and push

build nginx docker with build results

---

.github/workflows/inspection-report.yml
.github/workflows/webapp-deploy.yml

Fix gcloud missing for github actions

Add cloud sdk to github actions

---

packages/camera/package.json
packages/camera/src/components/Capture/hooks.js
yarn.lock

- iPhone 8 (crashes when spamming)
1. Take pictures

Added image compression before upload

---

packages/camera/src/components/Camera/hooks/useCamera.js
packages/camera/src/components/Capture/hooks.js
src/config/sentry.js
src/screens/InspectionCreate/index.js
src/screens/Landing/index.js

1. Take a picture 
2. Check in sentry issues

Enabled sentry logs only on web

---

src/screens/InspectionCapture/settings.js
src/screens/InspectionCapture/useFullscreen.js

- Mac air M1 chrome
1. Try toggle the fullscreen from camera settings

Added exit from fullscreen mode, and tracking the fullscreen state

---

packages/camera/src/components/Capture/capture.js
packages/camera/src/components/Layout/index.js
src/screens/InspectionCapture/styles.js

- Mac air m1 chrome
1. Land on the camera
2. Rotate to portrait mode

Fixed orientation screen background and positioning the layout

---

packages/visualization/src/components/DamageHighlight/index.js
services/inspection-report/package.json

Fix DamageHighlight options proptype

---

packages/camera/src/components/UploadCenter/index.js

- Web chrome
1. Just land on the upload center

Fixed upload center layout

---

package.json
packages/camera/package.json
packages/corejs/package.json
packages/cra-template/package.json
packages/openapi-specs-to-ts/package.json
packages/sights/package.json
packages/toolkit/package.json
packages/ui/package.json
packages/visualization/package.json

Release @monkvision/monkjs v2.4.1

---

packages/camera/src/components/Camera/hooks/useCamera.js
packages/camera/src/components/Camera/index.js
packages/camera/src/components/Capture/capture.js
packages/camera/src/components/Capture/hooks.js
src/hooks/useSnackbar/index.js
src/screens/InspectionCapture/index.js

Add warnings snackbar for compression and upload steps

---

.github/workflows/sentry-release.yml

Rename capture Sentry project name on Sentry release workflow

---

services/inspection-report/src/views/InspectionDetails/index.js
services/inspection-report/src/views/InspectionDetails/useGetPdfReport/index.js

- Mac web chrome
1. Go to ira 
2. Land on **insepctionDetails**
3. Check the download pdf button

Updated the pdf request payload

---

src/screens/InspectionCreate/index.js
src/screens/InspectionCreate/useCreateInspection/index.js
src/screens/Landing/index.js
src/screens/Landing/useGetPdfReport/index.js
src/screens/Landing/useUpdateOneTask/index.js

- Mac air chrome 
1. Finish all the inspection tasks
2. Hit download pdf once it got activated

Added pdf download and integrate it with snackbar

---

website/docs/js/api/components/Capture.md

Update Camera doc for Wasm error

---

.babelrc.json
src/i18n/resources/en.js
src/i18n/resources/fr.js
src/screens/Landing/index.js
src/screens/Landing/styles.js
webpack.config.js

Add SDK version number on homepage, either on header or footer. Version number should be updated dynamically as a variable
Get version number from `package.json` and show in the landing page

fix: add version in the landing page

---

packages/sights/README.md

fix: license is BSD and not MIT

---

packages/sights/index.json

This PR is to test the pipeline cycle for website build when we commit a change in packages/sights package...

fix: chnage the category for IqwSM3 sight

---

package.json
src/components/App.js
src/components/SilentAuth.js
src/components/SilentLang.js
src/config/sentry.js
src/config/sentryPlatform/index.js
src/config/sentryPlatform/index.native.js
src/hooks/useAuth/index.js
src/hooks/useSignIn/index.js
src/main.js
src/screens/Authentication/SignIn/index.js
src/screens/Authentication/SignOut/index.js
src/screens/InspectionCapture/index.js
src/screens/InspectionCreate/index.js
src/screens/InspectionCreate/useCreateInspection/index.js
src/screens/InspectionList/index.js
src/screens/InspectionPrompt/index.js
src/screens/InspectionVehicleUpdate/index.js
src/screens/Landing/LanguageSwitch/index.js
src/screens/Landing/SignOut/index.js
src/screens/Landing/index.js
yarn.lock

- Re-implemented sentry monitoring.

feat: re-implement sentry monitoring

---

packages/camera/src/components/Camera/hooks/useCamera.js

Fix stretched image issue for sights pic in Android tablet device (like Samsung Galaxy Tab A  Model: SM-T307U)
Recalculating the resolution(dimension) for canvas as per video's aspect ratio when drawing the image:
- If video's aspect ratio is 4:3, then canvas resolution would be either FHD (1920x1080) or QHD (2560x1440) based on selected resolution
- If video's aspect ratio is not 4:3 then going to calculate new resolution as per video's aspect ratio and set to canvas

Fix stretched image issue | HGreg

---

packages/camera/src/components/Capture/capture.js
packages/camera/src/components/Controls/index.js
packages/camera/src/components/Layout/PortraitLayout.js
packages/camera/src/components/Layout/index.js
src/screens/InspectionCapture/index.js

1. Created new PortraitLayout file which will be loaded when we are using VIN no. in portrait  mode
2. Modified capture.js ,setting.js, takePicture.js, controls/index.js,,
- when user selects vin number in portrait mode ,camera will be opened  to take picture
1. iphone 6/7/8, iphone 12 pro, pixel3
-
- 

implemented feature to allow portrait mode for taking VIN

---

packages/camera/src/components/AddDamageModal/PartSelector.js
packages/camera/src/components/AddDamageModal/index.js
src/components/Modal/styles.js

Fix/mn 178/minor fixes

---

src/screens/InspectionCapture/index.js

fixed code in handleSuccess from InspectionCapture.js
fixed pdf fetching issue at end of inspection
Desktop
-
- 
1.  take vin no. picture
2.  take damage detection
3. wait for some time
4. pdf download should be ready
5. click on download pdf and it should open pdf in another pdf

pdf fetching issue is resolved

---

package.json
packages/camera/package.json
packages/camera/src/components/Controls/FullScreenButton.js
packages/camera/src/components/Controls/TakePictureButton.js
packages/camera/src/components/Controls/index.js
packages/camera/src/i18n/resources/en.js
packages/camera/src/i18n/resources/fr.js
src/screens/InspectionCapture/index.js
yarn.lock

Replace settings button with full screen button
Added conditional based settings button which will toggle settings and full screen button.

feat: replace settings button with full screen(MN-197)

---

website/docs.sidebars.js
website/docs/js/api/components/Capture.md

Updated documentation for Camera components.

feat: update the capture component documentation (MN-204)

---

website/docs/monitoring.md

Update the Sentry doc with the required delay before redirect to another URL after the completion of successful Capture Tour...

update Sentry doc with the required delay before redirecting

---

packages/camera/src/components/Capture/capture.js
packages/corejs/src/monitoring/types.ts

Added Add damage metrics in SDK

feat: implememnt sentry add damage metrics (MN-239)

---

packages/inspection-report/package.json
packages/inspection-report/src/components/DamageReport.js
packages/inspection-report/src/components/index.js
packages/inspection-report/src/i18n/index.js
packages/inspection-report/src/i18n/resources/en.js
packages/inspection-report/src/i18n/resources/fr.js
packages/inspection-report/src/i18n/resources/index.js
packages/inspection-report/src/index.js
src/i18n/index.js

* Installed `i18next` and `react-i18next` packages in `inspection-report` package
* Initialised localisation
* add localisation instance for `inspection-report` package to change the language from demo app

Feature/mn 252/i18next

---

packages/camera/src/components/UploadCenter/UploadCard/hooks/useSubtitle.js

Logic change to map compliance error code with translation copy to show the error message on screen...

Logic change to find the matched error message with error code

---

packages/camera/src/components/Controls/index.js

Hide full screen button from iOS devices

feat: hide full screen button from iOS devices (MN-278)

---

app.config.js
packages/inspection-report/src/components/DamageReport/UpdateDamagePopUp/index.js
packages/inspection-report/src/components/DamageReport/hooks/useProcessInspection.js
src/screens/InspectionCreate/useCreateInspection/index.js

- Fixed a bug preventing the UpdateDamagePopUp to open
- Switched related images from damages to parts
- Fixed a bug causing the loading to display twice

Feature/mn 292/vm qa comments 3

---

website/docs/visualize-manipulate.md

Enhance the documentation available for the V&M package. The goal is to make the most detailed and clear documentation possible : imagine you are a client, that does not know anything about this package, and that is NOT a senior developer. You want to know what this package does and how to use it : you should be able to have all the required info in the package documentation.

add details about V&M package and how to use it

---

package.json
packages/camera/package.json
packages/camera/src/components/Overlay/hooks/useCustomSVGAttributes.js
packages/corejs/package.json
packages/cra-template/package.json
packages/inspection-report/package.json
packages/openapi-specs-to-ts/package.json
packages/sights/package.json
packages/toolkit/package.json
packages/ui/package.json
packages/visualization/package.json

Upgrade @MonkVision NPM packages from `v3.7.8` to `v3.7.9`

upgrade @monkvision packages from v3.7.8 to v3.7.9

---

packages/camera/src/components/AddDamageModal/index.js

Centered image on add damage modal

---

packages/inspection-report/src/components/DamageReport/Accordion.js
packages/inspection-report/src/components/DamageReport/DamageReport.js
packages/inspection-report/src/components/DamageReport/UpdateDamagePopUp/index.js
packages/inspection-report/src/components/DamageReport/hooks/useDamageReportStateHandlers.js
packages/inspection-report/src/components/DamageReport/hooks/useProcessInspection.js
packages/inspection-report/src/components/Gallery/index.js
packages/inspection-report/src/i18n/resources/en.js
packages/inspection-report/src/i18n/resources/fr.js

Update layout of desktop mode for inspection report page

feat: update layout of inspection report for desktop mode (MN-359)

---

src/contexts/clients/clients.js
src/contexts/clients/info/index.js
src/contexts/clients/info/videoPoc.js
src/contexts/clients/palettes/index.js
src/contexts/clients/sights/index.js
src/contexts/clients/workflows/index.js
src/screens/paramsMap.js

Client Id for video poc : **e5j**

feat: add new client video poc (MN-415)

---

packages/camera/src/components/Camera/index.js

Added zIndex: -1 and controlsList

fix: added zIndex and controlslist

---

packages/corejs/package.json
packages/corejs/src/tasks/index.ts
src/screens/InspectionCapture/index.js
yarn.lock

Implement retry logic when HTTP request fails for damage-detection TASKs.

Retry functionality when HTTP request fails for TASK

---

packages/corejs/src/tasks/index.ts
packages/corejs/test/tasks.test.ts
packages/corejs/test/utils/axiosMock.utils.ts
src/screens/InspectionCapture/index.js

Fix ESLint and Jest issues in core package for `webapp/demo-capture` branch too

Webapp - Fix eslint & jest issues in core package

---

packages/corejs/package.json
packages/corejs/src/tasks/index.ts
packages/corejs/test/tasks.test.ts
packages/corejs/test/utils/axiosMock.utils.ts
yarn.lock

Implement retry logic when HTTP request fails for updating the damage-detection TASKs.

Main - Core Package - API retry functionality for updating tasks

---

apps/demo-app/.env-cmdrc.json
apps/demo-app/package.json

Created a development build configuration to build the demo app.

Added a development build configuration for the demo app

---

apps/drive-app/src/pages/PhotoCapturePage/PhotoCapturePage.tsx
apps/drive-app/test/pages/PhotoCapturePage.test.tsx
packages/network/src/api/image/requests.ts
packages/network/src/api/models/image.ts
packages/network/src/api/models/task.ts
packages/network/test/api/image/requests.test.ts
packages/types/src/state/image.ts
packages/types/src/state/task.ts

Jira Ticket Reference : [MN-509](https://acvauctions.atlassian.net/browse/MN-509)
Add logic to implement the live compliance in the project.
- [x ] I have updated the unit tests based on the changes I made
- [x ] I have updated the docs (TSDoc / README / global doc) to reflect my changes
- [x ] I have performed self-QA of my feature by testing the apps and packages and made sure that :
[MN-509]: https://acvauctions.atlassian.net/browse/MN-509?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Live Compliance

---

apps/drive-app/src/config/sights.ts
configs/test-utils/src/__mocks__/@monkvision/common.tsx
packages/common-ui-web/src/components/InspectionGallery/hooks/useInspectionGalleryItems.ts
packages/common-ui-web/test/components/InspectionGallery/hooks/useInspectionGalleryItems.test.ts
packages/common/README/UTILITIES.md
packages/common/src/utils/index.ts
packages/common/src/utils/state.utils.ts
packages/common/test/utils/state.utils.test.ts
packages/inspection-capture-web/src/PhotoCapture/PhotoCapture.tsx
packages/inspection-capture-web/src/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUD.tsx
packages/inspection-capture-web/src/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUDButtons/PhotoCaptureHUDButtons.styles.ts
packages/inspection-capture-web/src/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUDButtons/PhotoCaptureHUDButtons.tsx
packages/inspection-capture-web/src/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUDButtons/hooks.ts
packages/inspection-capture-web/src/PhotoCapture/PhotoCaptureHUD/hooks/index.ts
packages/inspection-capture-web/src/PhotoCapture/PhotoCaptureHUD/hooks/useComplianceNotification.ts
packages/inspection-capture-web/src/PhotoCapture/hooks/usePhotoCaptureSightState.ts
packages/inspection-capture-web/src/PhotoCapture/hooks/useUploadQueue.ts
packages/inspection-capture-web/test/PhotoCapture/PhotoCapture.test.tsx
packages/inspection-capture-web/test/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUD.test.tsx
packages/inspection-capture-web/test/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUDButtons.test.tsx
packages/inspection-capture-web/test/PhotoCapture/PhotoCaptureHUD/hooks/useComplianceNotification.test.ts

Jira Ticket Reference : [MN-509](https://acvauctions.atlassian.net/browse/MN-509)
- Fix the Sights of the Drive App (left and right steering wheel sights were switched)
- Fix the live compliance not being enabled on both apps
- Added Compliance notification badge on the gallery button
- [ x ] I have updated the unit tests based on the changes I made
- [ x ] I have updated the docs (TSDoc / README / global doc) to reflect my changes
- [ x ] I have performed self-QA of my feature by testing the apps and packages and made sure that :
[MN-509]: https://acvauctions.atlassian.net/browse/MN-509?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZj …

Fix live compliance

---

apps/drive-app/src/pages/PhotoCapturePage/PhotoCapturePage.tsx

Disable compliance for drive-app

---

apps/drive-app/src/pages/PhotoCapturePage/PhotoCapturePage.tsx
apps/drive-app/test/pages/PhotoCapturePage.test.tsx

Allow skip retake for drive app

---

apps/drive-app/src/pages/PhotoCapturePage/PhotoCapturePage.tsx
apps/drive-app/test/pages/PhotoCapturePage.test.tsx
configs/test-utils/src/__mocks__/@monkvision/common.tsx

Jira Ticket Reference : [MN-514](https://acvauctions.atlassian.net/browse/MN-514)
Allows users to specify an URL param which will be the redirect to link when the inspection is done.
[MN-514]: https://acvauctions.atlassian.net/browse/MN-514?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Added redirect to custom url drive-app

---

packages/common-ui-web/src/components/InspectionGallery/hooks/useInspectionGalleryItems.ts
packages/common-ui-web/src/components/InspectionGallery/types.ts
packages/inspection-capture-web/src/PhotoCapture/PhotoCapture.tsx
packages/network/test/api/image/mappers.test.ts

Jira Ticket Reference : [MN-XXX](https://acvauctions.atlassian.net/browse/MN-XXX)

Fix 'Add Damage' button hidden in gallery

---

packages/common-ui-web/src/components/InspectionGallery/hooks/useInspectionGalleryItems.ts
packages/common-ui-web/test/components/InspectionGallery/hooks/useInspectionGalleryItems.test.ts
packages/inspection-capture-web/src/PhotoCapture/hooks/useUploadQueue.ts
packages/inspection-capture-web/test/PhotoCapture/hooks/useUploadQueue.test.ts

Jira Ticket Reference : [MN-520](https://acvauctions.atlassian.net/browse/MN-520)
[MN-520]: https://acvauctions.atlassian.net/browse/MN-520?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix wrong picture displayed in gallery

---

packages/common-ui-web/src/components/InspectionGallery/hooks/useInspectionGalleryItems.ts
packages/inspection-capture-web/src/PhotoCapture/PhotoCapture.tsx
packages/inspection-capture-web/test/PhotoCapture/PhotoCapture.test.tsx
packages/network/src/api/image/mappers.ts
packages/network/src/api/models/compliance.ts
packages/network/test/api/image/mappers.test.ts
packages/types/src/state/image.ts

Jira Ticket Reference : [MN-523](https://acvauctions.atlassian.net/browse/MN-523)
Added logic to handle custom thresholds for compliance checks.
[MN-523]: https://acvauctions.atlassian.net/browse/MN-523?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Added custom compliance thresholds logic

---

apps/demo-app/public/index.html
apps/demo-app/src/config/compliance.ts
apps/demo-app/src/config/index.ts
apps/demo-app/src/pages/PhotoCapturePage/PhotoCapturePage.tsx
apps/drive-app/public/index.html
apps/drive-app/src/config/compliance.ts
apps/drive-app/src/pages/PhotoCapturePage/PhotoCapturePage.tsx
apps/renault-demo-app/public/index.html

Disable the WRONG_ANGLE compliance issue in demo and drive apps

---

packages/sights/research/data/audia7/audia7.json
packages/sights/research/data/fesc20/fesc20.json
packages/sights/research/data/ff150/ff150.json
packages/sights/research/data/ffocus18/ffocus18.json
packages/sights/research/data/ftransit18/ftransit18.json
packages/sights/research/data/haccord/haccord.json
packages/sights/research/data/jgc21/jgc21.json
packages/sights/research/data/labels.json
packages/sights/research/data/tsienna20/tsienna20.json
packages/sights/research/data/vwtroc/vwtroc.json

Jira Ticket Reference : [MN-536](https://acvauctions.atlassian.net/browse/MN-536)
- Updated the taxonomy for certain viewpoints :
- Front fender left → front left
- Front fender right → front right
- Lateral full right → Full right
- Lateral full left → Full left
[MN-536]: https://acvauctions.atlassian.net/browse/MN-536?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Updated the taxonomy for some viewpoints

---

apps/demo-app/src/config/compliance.ts
apps/drive-app/src/config/compliance.ts

Jira Ticket Reference : [MN-537](https://acvauctions.atlassian.net/browse/MN-537)
Re-activate the car coverage compliance in Demo and Drive apps
[MN-537]: https://acvauctions.atlassian.net/browse/MN-537?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Reactivated car cov compliance in drive and demo apps

---

README.md
packages/sights/research/data/audia7/audia7.json
packages/sights/research/data/fesc20/fesc20.json
packages/sights/research/data/ff150/ff150.json
packages/sights/research/data/ffocus18/ffocus18.json
packages/sights/research/data/ftransit18/ftransit18.json
packages/sights/research/data/haccord/haccord.json
packages/sights/research/data/jgc21/jgc21.json
packages/sights/research/data/labels.json
packages/sights/research/data/tsienna20/tsienna20.json
packages/sights/research/data/vwtroc/vwtroc.json

Jira Ticket References : 
- [MN-535](https://acvauctions.atlassian.net/browse/MN-535)
- [MN-536](https://acvauctions.atlassian.net/browse/MN-536)
- Revert the changes made to some viewpoint label keys (but kept the taxonomy changes)
- Added `wheel_analysis` task to some sights used by the Drive app
[MN-535]: https://acvauctions.atlassian.net/browse/MN-535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MN-536]: https://acvauctions.atlassian.net/browse/MN-536?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix Drive sights

---

apps/drive-app/src/config.ts

Jira Ticket Reference : [MN-515](https://acvauctions.atlassian.net/browse/MN-515)
Disabled add damage and added back HinL to Drive app
[MN-515]: https://acvauctions.atlassian.net/browse/MN-515?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Disabled add damage and added back HinL to Drive app

---

apps/demo-app/src/config.ts
apps/drive-app/src/config.ts
apps/renault-demo-app/src/config.ts

Jira Ticket Reference : [MN-515](https://acvauctions.atlassian.net/browse/MN-515)
Enabled back live compliance in apps
[MN-515]: https://acvauctions.atlassian.net/browse/MN-515?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Enabled back live compliance in apps

---

apps/demo-app/src/config.ts
apps/drive-app/src/config.ts

Jira Ticket Reference : [MN-515](https://acvauctions.atlassian.net/browse/MN-515)
Allow skip retake in apps
[MN-515]: https://acvauctions.atlassian.net/browse/MN-515?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Allow skip retake in apps

---

documentation/docs/packages/_category_.json
documentation/docs/v3-docs/_category_.json

Jira Ticket Reference : [MN-538](https://acvauctions.atlassian.net/browse/MN-538)
Updated the position of the pages in the docs sidebar
[MN-538]: https://acvauctions.atlassian.net/browse/MN-538?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Updated the position of the pages in the docs sidebar

---

apps/demo-app/src/config.ts

Disabled some compliance issues in Demo App

Disabled some compliance issues in Demo App

---

apps/demo-app/src/pages/LoginPage/LoginPage.tsx
apps/demo-app/src/sentry.ts
apps/drive-app/src/pages/LoginPage/LoginPage.tsx
apps/drive-app/src/sentry.ts
apps/renault-demo-app/src/pages/LoginPage/LoginPage.tsx
apps/renault-demo-app/src/sentry.ts
configs/test-utils/src/__mocks__/@monkvision/monitoring.tsx
configs/test-utils/src/__mocks__/jwt-decode.ts
packages/common-ui-web/src/components/CreateInspection/CreateInspection.tsx
packages/common-ui-web/src/components/Login/Login.tsx
packages/common/package.json
packages/common/src/apps/appStateProvider.tsx
packages/common/src/apps/monitoring.ts
packages/common/test/apps/appStateProvider.test.tsx
packages/monitoring/src/adapters/adapter.ts
packages/monitoring/src/adapters/emptyAdapter.ts
packages/monitoring/src/react/hooks.ts
packages/monitoring/test/adapters/emptyAdapter.test.ts
packages/monitoring/test/react/provider.test.tsx
packages/sentry/package.json
packages/sentry/src/adapter.ts
packages/sentry/test/adapter.test.ts
yarn.lock

Jira Ticket Reference : [MN-542](https://acvauctions.atlassian.net/browse/MN-542)
- Fix the monitoring by updating the environment, user id, inspection id etc.
[MN-542]: https://acvauctions.atlassian.net/browse/MN-542?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix MonkJs Monitoring

---

apps/demo-app/public/index.html
apps/demo-app/src/config.ts
apps/drive-app/.env-cmdrc.json
apps/drive-app/public/index.html
apps/drive-app/src/config.ts
apps/renault-demo-app/public/index.html
documentation/src/css/custom.css

- Change React App descriptions
- Disabled VQA and Zoom compliance issues for the Rear pickup Sight
- Prevent overscroll in Documentation app
- Disable skip retake for Drive in production

Small updates

---

apps/renault-demo-app/src/config.ts

Updated the config for Renault app

Updated the config for Renault app

---

packages/inspection-capture-web/src/PhotoCapture/hooks/useUploadQueue.ts
packages/inspection-capture-web/test/PhotoCapture/hooks/useUploadQueue.test.ts

Jira Ticket Reference : [MN-548](https://acvauctions.atlassian.net/browse/MN-548)
Added no connection to the bad connection warning causes
[MN-548]: https://acvauctions.atlassian.net/browse/MN-548?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Added no connection to the bad connection warning causes

---

yarn.lock

Updated the browserlist

---

apps/demo-app/src/index.tsx
apps/drive-app/src/index.tsx
apps/renault-demo-app/src/index.tsx

Jira Ticket Reference : [MN-546](https://acvauctions.atlassian.net/browse/MN-546)
Turns out the Sentry envelope issue was probably fixed when we switched to `.toBlob` in the camera screenshot logic, so I re-enabled Sentry and Posthog in the apps.
[MN-546]: https://acvauctions.atlassian.net/browse/MN-546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Re-enabled Sentry and Posthog

---

apps/drive-app/src/config.ts
configs/test-utils/src/__mocks__/@monkvision/monitoring.tsx
packages/camera-web/src/Camera/hooks/useUserMedia.ts
packages/common-ui-web/src/components/CreateInspection/CreateInspection.tsx
packages/common-ui-web/src/components/ImageDetailedView/ImageDetailedViewOverlay/hooks.ts
packages/common-ui-web/src/components/InspectionGallery/InspectionGalleryItemCard/hooks.ts
packages/common-ui-web/src/components/Login/Login.tsx
packages/common-ui-web/test/components/ImageDetailedView/ImageDetailedViewOverlay/hooks.test.ts
packages/common-ui-web/test/components/InspectionGallery/InspectionGalleryItemCard/InspectionGalleryItemCard.test.tsx
packages/common-ui-web/test/components/InspectionGallery/InspectionGalleryItemCard/hooks.test.ts
packages/common/src/i18n/translations/image.ts
packages/inspection-capture-web/src/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUD.tsx
packages/inspection-capture-web/src/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUDElementsSight/SightSlider/SightSliderButton.tsx
packages/inspection-capture-web/src/PhotoCapture/hooks/useUploadQueue.ts
packages/inspection-capture-web/test/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUD.test.tsx
packages/inspection-capture-web/test/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUDElementsSight/SightSlider/SightSliderButton.test.tsx
packages/monitoring/README.md
packages/monitoring/src/adapters/adapter.ts
packages/monitoring/src/adapters/debugAdapter.ts
packages/monitoring/src/adapters/emptyAdapter.ts
packages/monitoring/test/adapters/debugAdapter.test.ts
packages/network/src/api/image/requests.ts
packages/network/src/api/react.ts
packages/network/test/api/image/requests.test.ts
packages/network/test/api/react.test.ts
packages/sentry/src/adapter.ts
packages/sentry/test/adapter.test.ts
packages/types/src/state/image.ts

Jira Ticket Reference : [MN-557](https://acvauctions.atlassian.net/browse/MN-557)
- Updated the Drive Sights config
- Fixed the error messages styles in Login and CreateInspection components ([MN-547](https://acvauctions.atlassian.net/browse/MN-547))
- Added HTTP error response body in Sentry logs
- Fixed a memory leak in the Camera component
- Added UPLOAD_ERROR image status
- Fixed an issue causing the retake count to not include upload errors
[MN-557]: https://acvauctions.atlassian.net/browse/MN-557?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MN-547]: …

Upload Error Status

---

packages/common-ui-web/src/components/Login/Login.styles.ts

Jira Ticket Reference : [MN-547](https://acvauctions.atlassian.net/browse/MN-547)
Change login Error message appearance
[MN-547]: https://acvauctions.atlassian.net/browse/MN-547?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

💄 make login error message look good on vertical

---

packages/common-ui-web/src/components/ImageDetailedView/ImageDetailedViewOverlay/hooks.ts
packages/common-ui-web/src/components/InspectionGallery/hooks/useItemListFillers.ts
packages/common-ui-web/src/components/VehicleTypeSelection/VehicleTypeSelection.styles.ts
packages/common-ui-web/src/components/VehicleTypeSelection/VehicleTypeSelection.tsx
packages/common-ui-web/test/components/InspectionGallery/hooks/useItemListFillers.test.ts
packages/common/src/hooks/useResponsiveStyle.ts
packages/common/src/hooks/useWindowDimensions.ts
packages/inspection-capture-web/src/PhotoCapture/PhotoCapture.tsx

Jira Ticket Reference : [MN-550](https://acvauctions.atlassian.net/browse/MN-550)
On a larger screen, It shouldn't have much of a difference.
But on a smaller screen, the center sliding should be centered in all the scenarios, and confirm button should come down.
[MN-550]: https://acvauctions.atlassian.net/browse/MN-550?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Vehicle selection looks good on smaller screen

---

packages/common-ui-web/README.md
packages/common-ui-web/src/components/VehicleTypeSelection/VehicleTypeSelection.styles.ts
packages/common-ui-web/src/components/VehicleTypeSelection/VehicleTypeSelection.tsx
packages/common-ui-web/test/components/VehicleTypeSelection/VehicleTypeSelection.test.tsx
packages/common/src/state/actions/index.ts
packages/common/src/state/actions/monkAction.ts
packages/common/src/state/actions/updatedVehicle.ts
packages/common/test/state/actions/updatedVehicle.test.ts
packages/network/README.md
packages/network/src/api/api.ts
packages/network/src/api/index.ts
packages/network/src/api/inspection/mappers.ts
packages/network/src/api/models/vehicle.ts
packages/network/src/api/react.ts
packages/network/src/api/vehicle/index.ts
packages/network/src/api/vehicle/mappers.ts
packages/network/src/api/vehicle/requests.ts
packages/network/test/api/inspection/data/apiInspectionGet.data.ts
packages/types/src/state/vehicle.ts

Jira Ticket Reference : [MN-553](https://acvauctions.atlassian.net/browse/MN-553)
When a vehicle type is selected and validated,  a PATCH request will be send to update the type of the vehicle. 
At the start of the component, if a vehlcle type is found in the fetched inspection, `onSelectVehicleType` callback will be called immedialty.
[MN-553]: https://acvauctions.atlassian.net/browse/MN-553?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Store the vehicle type in the inspection

---

documentation/.eslintrc.js
documentation/docusaurus.config.js
documentation/package.json
documentation/src/components/ConfigValidator/ConfigImport/ConfigImport.module.css
documentation/src/components/ConfigValidator/ConfigImport/ConfigImport.tsx
documentation/src/components/ConfigValidator/ConfigImport/index.ts
documentation/src/components/ConfigValidator/ConfigValidateResults/ConfigValidateResults.module.css
documentation/src/components/ConfigValidator/ConfigValidateResults/ConfigValidateResults.tsx
documentation/src/components/ConfigValidator/ConfigValidateResults/index.ts
documentation/src/components/ConfigValidator/index.ts
documentation/src/components/index.ts
documentation/src/css/custom.css
documentation/src/pages/ConfigValidator/index.tsx
documentation/src/pages/ConfigValidator/styles.module.css
documentation/src/utils/index.ts
documentation/src/utils/schemas.ts
packages/types/src/config.ts
yarn.lock

Jira Ticket Reference : [MN-560](https://acvauctions.atlassian.net/browse/MN-560)
Added live configs validator in global doc
[MN-560]: https://acvauctions.atlassian.net/browse/MN-560?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Added live configs validator in global doc

---

apps/demo-app/src/posthog.ts
apps/drive-app/src/posthog.ts
apps/lux-demo-app/src/posthog.ts
apps/renault-demo-app/src/posthog.ts
packages/common-ui-web/src/components/CreateInspection/CreateInspection.tsx
packages/common-ui-web/src/components/Login/Login.tsx
packages/common-ui-web/src/components/VehicleTypeSelection/VehicleTypeSelection.tsx
packages/common-ui-web/test/components/VehicleTypeSelection/VehicleTypeSelection.test.tsx
packages/common/package.json
packages/common/src/apps/analytics.ts
packages/common/src/apps/appStateProvider.tsx
packages/inspection-capture-web/src/PhotoCapture/PhotoCapture.tsx
packages/inspection-capture-web/src/PhotoCapture/hooks/index.ts
packages/inspection-capture-web/src/PhotoCapture/hooks/usePhotoCaptureSightState.ts
packages/inspection-capture-web/src/PhotoCapture/hooks/useTracking.ts
packages/inspection-capture-web/test/PhotoCapture/PhotoCapture.test.tsx
packages/inspection-capture-web/test/PhotoCapture/hooks/useTracking.test.ts
packages/network/src/api/api.ts
packages/network/src/api/react.ts
packages/network/src/api/vehicle/requests.ts
packages/posthog/package.json
yarn.lock

- Added analytics `setUserId` when inspectionId is passed as URL params.
- Added analytics and monitoring app state in common-ui-web component: `selectVehicleType`, `login`, `createInspection`.

Fixed analytics + added monitoring & analytics state

---

packages/sights/research/data/tsienna20/tsienna20.json

Jira Ticket Reference : [MN-563](https://acvauctions.atlassian.net/browse/MN-563)
Change sight_label for sight_id  tsienna20-qA3aAUUq from rear to rear-low
- Check its changing on UI of document
[MN-563]: https://acvauctions.atlassian.net/browse/MN-563?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

📚 change tsienna20-qA3aAUUq as rear-low

---

apps/drive-app/src/posthog.ts

Added drive own token project posthog

Add new posthog token to drive

---

documentation/package.json
documentation/src/components/ConfigValidator/ConfigImport/ConfigImport.tsx
documentation/src/components/ConfigValidator/ConfigValidateResults/ConfigValidateResults.tsx
documentation/src/utils/schemas.ts
yarn.lock

Jira Ticket Reference : [MN-565](https://acvauctions.atlassian.net/browse/MN-565)
Added custom validators for the Live Config validator in the global doc
[MN-565]: https://acvauctions.atlassian.net/browse/MN-565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Custom Live Config validators

---

packages/inspection-capture-web/src/PhotoCapture/hooks/usePhotoCaptureSightState.ts

Added lastSightSelected tag for churn by view point in posthog

---

apps/demo-app/src/pages/PhotoCapturePage/PhotoCapturePage.tsx
apps/demo-app/test/pages/PhotoCapturePage.test.tsx
apps/drive-app/src/pages/PhotoCapturePage/PhotoCapturePage.tsx
apps/drive-app/test/pages/PhotoCapturePage.test.tsx
apps/lux-demo-app/src/pages/PhotoCapturePage/PhotoCapturePage.tsx
apps/renault-demo-app/src/pages/PhotoCapturePage/PhotoCapturePage.tsx

Jira Ticket Reference : [MN-571](https://acvauctions.atlassian.net/browse/MN-571)
Spread capture app config in PhotoCapture component in all apps in order to fix the HINL task not being present in the Drive app
[MN-571]: https://acvauctions.atlassian.net/browse/MN-571?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix HINL task not in Drive staging app

---

packages/sights/research/data/vehicles.json

Changed city to hatchback for Fordfocus

---

packages/inspection-capture-web/src/PhotoCapture/PhotoCapture.tsx
packages/inspection-capture-web/src/PhotoCapture/hooks/useComplianceAnalytics.ts
packages/inspection-capture-web/src/PhotoCapture/hooks/usePhotoCaptureSightState.ts
packages/inspection-capture-web/test/PhotoCapture/PhotoCapture.test.tsx
packages/inspection-capture-web/test/PhotoCapture/hooks/useComplianceAnalytics.test.ts
packages/inspection-capture-web/test/PhotoCapture/hooks/usePhotoCaptureSightState.test.ts

Fixed compliances posthog events resend after page refresh

---

packages/inspection-capture-web/src/PhotoCapture/PhotoCapture.tsx

Added inspection completed to sightselected posthog tag

---

apps/drive-app/.env-cmdrc.json
apps/drive-app/package.json

Jira Ticket Reference : [MN-576](https://acvauctions.atlassian.net/browse/MN-576)
[MN-576]: https://acvauctions.atlassian.net/browse/MN-576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Added admin env to drive app

---

packages/inspection-capture-web/src/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUDButtons/PhotoCaptureHUDButtons.styles.ts

Jira Ticket Reference : [MN-578](https://acvauctions.atlassian.net/browse/MN-578)
Lowered the opacity of the PhotoCapture buttons background
[MN-578]: https://acvauctions.atlassian.net/browse/MN-578?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Lowered the opacity of the PhotoCapture buttons background

---

apps/demo-app/src/local-config.json
apps/drive-app/src/local-config.json
apps/lux-demo-app/src/local-config.json
apps/renault-demo-app/src/local-config.json
documentation/src/utils/schemas.ts
packages/common-ui-web/src/components/InspectionGallery/InspectionGallery.tsx
packages/common-ui-web/src/components/InspectionGallery/InspectionGalleryItemCard/InspectionGalleryItemCard.tsx
packages/common-ui-web/src/components/InspectionGallery/InspectionGalleryItemCard/hooks.ts
packages/common-ui-web/src/components/InspectionGallery/types.ts
packages/common-ui-web/test/components/InspectionGallery/InspectionGalleryItemCard/InspectionGalleryItemCard.test.tsx
packages/common-ui-web/test/components/InspectionGallery/hooks/useInspectionGalleryItems.test.ts
packages/common/README/HOOKS.md
packages/common/src/hooks/index.ts
packages/common/src/hooks/useThumbnail.ts
packages/common/test/hooks/useThumbnail.test.ts
packages/inspection-capture-web/src/PhotoCapture/PhotoCapture.tsx
packages/inspection-capture-web/test/PhotoCapture/PhotoCapture.test.tsx
packages/types/src/config.ts
packages/types/src/state/image.ts

Jira Ticket Reference : [MN-574](https://acvauctions.atlassian.net/browse/MN-574)
Implemented a custom hook to get the thumbnail url of a image using `resize_image` microservice.
Inspection gallery uses this thumbnail instead of the original picture.
[MN-574]: https://acvauctions.atlassian.net/browse/MN-574?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Added thumbnail feature

---

packages/common-ui-web/src/components/InspectionGallery/hooks/useInspectionGalleryItems.ts

Jira Ticket Reference : [MN-579](https://acvauctions.atlassian.net/browse/MN-579)
[MN-579]: https://acvauctions.atlassian.net/browse/MN-579?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fixed image with upload error status are displayed on top of the gallery

---

packages/analytics/package.json
packages/camera-web/package.json
packages/common-ui-web/package.json
packages/common/package.json
packages/inspection-capture-web/package.json
packages/monitoring/package.json
packages/network/package.json
packages/posthog/package.json
packages/sentry/package.json
packages/sights/package.json
packages/types/package.json
yarn.lock

Jira Ticket Reference : [MN-592](https://acvauctions.atlassian.net/browse/MN-592)
Fixed some issues after first NPM deployment
[MN-592]: https://acvauctions.atlassian.net/browse/MN-592?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Clean up NPM deploy errors

---

configs/svgo-config/package.json

Jira Ticket Reference : [MN-600](https://acvauctions.atlassian.net/browse/MN-600)
- Made svgo-config public

Made SVGO-config public

---

documentation/src/components/Shared/CopyPopup/CopyPopup.tsx
documentation/src/components/Shared/SearchBar/SearchBar.tsx
packages/camera-web/src/SimpleCameraHUD/SimpleCameraHUD.tsx
packages/common-ui-web/src/components/Button/Button.tsx
packages/common-ui-web/src/components/CreateInspection/CreateInspection.tsx
packages/common-ui-web/src/components/ImageDetailedView/ImageDetailedView.tsx
packages/common-ui-web/src/components/InspectionGallery/InspectionGallery.tsx
packages/common-ui-web/src/components/InspectionGallery/InspectionGalleryTopBar/InspectionGalleryTopBar.tsx
packages/common-ui-web/src/components/InspectionGallery/translations/de.json
packages/common-ui-web/src/components/InspectionGallery/translations/en.json
packages/common-ui-web/src/components/InspectionGallery/translations/fr.json
packages/common-ui-web/src/components/InspectionGallery/translations/nl.json
packages/common-ui-web/src/components/InspectionGallery/types.ts
packages/common-ui-web/src/components/Login/Login.tsx
packages/common-ui-web/src/components/TakePictureButton/TakePictureButton.tsx
packages/common-ui-web/src/components/VehicleTypeSelection/VehicleTypeSelection.tsx
packages/common-ui-web/test/components/InspectionGallery/InspectionGalleryTopBar/InspectionGalleryTopBar.test.tsx
packages/common/README/INTERNATIONALIZATION.md
packages/common/src/i18n/utils.tsx
packages/inspection-capture-web/src/PhotoCapture/PhotoCapture.tsx
packages/inspection-capture-web/src/PhotoCapture/PhotoCaptureHOC.tsx
packages/inspection-capture-web/src/PhotoCapture/hooks/usePhotoCaptureSightState.ts
packages/inspection-capture-web/test/PhotoCapture/hooks/usePhotoCaptureSightState.test.ts

Jira Ticket Reference : [MN-603](https://acvauctions.atlassian.net/browse/MN-603)
[MN-603]: https://acvauctions.atlassian.net/browse/MN-603?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat/mn 603/validate message insterd of button

---

packages/common/src/apps/appState.ts
packages/common/src/apps/appStateProvider.tsx
packages/common/test/apps/appStateProvider.test.tsx

Jira Ticket Reference : [MN-615](https://acvauctions.atlassian.net/browse/MN-615)
Added availableVehicleTypes in the AppState context
[MN-615]: https://acvauctions.atlassian.net/browse/MN-615?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Added availableVehicleTypes in the AppState context

---

packages/common/src/i18n/translations/vehicleParts.ts
packages/types/src/state/part.ts

\## Overview
Jira Ticket Reference : [MN-616](https://acvauctions.atlassian.net/browse/MN-616)
Added car_inside, damaged_car_inside and handle_back_center vehicle parts
[MN-616]: https://acvauctions.atlassian.net/browse/MN-616?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Added car_inside, damaged_car_inside and handle_back_center vehicle parts

---

packages/sentry/src/adapter.ts

Jira Ticket Reference : [MN-XXX](https://acvauctions.atlassian.net/browse/MN-XXX)
Removed console log added by mistake in the SentryMonitoringAdapter class

Removed console log added by mistake in the SentryMonitoringAdapter class

---

packages/common/README/INTERNATIONALIZATION.md
packages/common/src/i18n/translations/damageTypes.ts
packages/common/src/i18n/translations/index.ts
packages/sentry/src/adapter.ts

Jira Ticket Reference : [MN-XXX](https://acvauctions.atlassian.net/browse/MN-XXX)

Feat/mn 616/damage type i18n

---

documentation/src/utils/schemas.ts
packages/network/src/api/inspection/mappers.ts
packages/network/test/api/inspection/data/apiInspectionPost.data.json
packages/network/test/api/inspection/data/apiInspectionPost.data.ts
packages/types/src/api.ts

Added pricingV2 option in CreateInspectionOptions

Added pricingV2 option in CreateInspectionOptions

---

packages/inspection-capture-web/src/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUDElementsSight/SightGuideline/SightGuideline.tsx
packages/inspection-capture-web/src/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUDTutorial/PhotoCaptureHUDTutorial.styles.ts
packages/inspection-capture-web/src/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUDTutorial/PhotoCaptureHUDTutorial.tsx
packages/inspection-capture-web/src/translations/de.json
packages/inspection-capture-web/src/translations/en.json
packages/inspection-capture-web/src/translations/fr.json
packages/inspection-capture-web/src/translations/nl.json

Added default message to sightGuidelines

---

packages/common/README/UTILITIES.md
packages/common/src/apps/appStateProvider.tsx
packages/common/src/utils/config.utils.ts
packages/common/src/utils/index.ts
packages/common/test/apps/appStateProvider.test.tsx
packages/common/test/utils/config.utils.test.ts

Jira Ticket Reference : [MN-617](https://acvauctions.atlassian.net/browse/MN-617)
Added getAvailableVehicleTypes util function
[MN-617]: https://acvauctions.atlassian.net/browse/MN-617?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Added getAvailableVehicleTypes util function

---

packages/common/src/state/actions/createdOneDamage.ts
packages/common/src/state/actions/deletedOneDamage.ts
packages/common/test/state/actions/createdOneDamage.test.ts
packages/common/test/state/actions/deletedOneDamage.test.ts

Added damageIds in parts entities when damage is created or deleted

---

packages/common/README/STATE_MANAGEMENT.md
packages/common/src/state/actions/createdOneDamage.ts
packages/common/src/state/actions/createdOnePricing.ts
packages/network/src/api/damage/requests.ts
packages/network/src/api/pricing/requests.ts
packages/network/test/api/damage/requests.test.ts
packages/network/test/api/pricing/requests.test.ts

Added local damage / pricing state before api request

---

packages/common/src/state/actions/createdOneDamage.ts

Fixed parts entities not updated properly when adding a damage

---

packages/network/src/api/inspection/mappers.ts
packages/network/test/api/inspection/data/apiInspectionPost.data.json

Changed "toyota" to "default" in output_format

---

packages/network/src/api/inspection/mappers.ts
packages/network/test/api/inspection/data/apiInspectionPost.data.json

Change damage_severity to 'toyota'

---

packages/network/src/api/inspection/requests.ts

Removed Union type in getInspections function

---

packages/network/README.md
packages/network/src/api/api.ts
packages/network/src/api/inspection/mappers.ts
packages/network/src/api/inspection/requests.ts
packages/network/src/api/models/inspection.ts
packages/network/src/api/react.ts
packages/network/test/api/inspection/requests.test.ts

Jira Ticket Reference : [MN-657](https://acvauctions.atlassian.net/browse/MN-657)
Added `getInspectionsCount` route.
[MN-657]: https://acvauctions.atlassian.net/browse/MN-657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Added getInspectionsCount route

---

packages/network/src/api/inspection/mappers.ts
packages/network/src/api/models/vehicle.ts
packages/network/src/api/vehicle/mappers.ts
packages/network/test/api/inspection/data/apiInspectionPost.data.json

Fixed the vehicle mapping for the POST request (structure differs from the GET mapping).

Fixed vehicle api mapping for POST request

---

packages/network/src/api/inspection/mappers.ts
packages/network/src/api/models/inspection.ts

Fixed api mapping sort

---

packages/network/src/auth/hooks.ts
packages/network/test/auth/hooks.test.ts

Jira Ticket Reference : [MN-656](https://acvauctions.atlassian.net/browse/MN-656)
Allow passing the Auth0 context to the useAuth hook
[MN-656]: https://acvauctions.atlassian.net/browse/MN-656?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Allow passing the Auth0 context to the useAuth hook

---

packages/network/src/auth/token.ts

Jira Ticket Reference : [MN-656](https://acvauctions.atlassian.net/browse/MN-656)
Added azp field in MonkJwtPayload type

Added azp field in MonkJwtPayload type

---

packages/common/src/apps/appStateProvider.tsx
packages/common/src/hooks/index.ts

Jira Ticket Reference : [MN-656](https://acvauctions.atlassian.net/browse/MN-656)
Fixed wrong export for useIsMounted hook
[MN-656]: https://acvauctions.atlassian.net/browse/MN-656?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fixed wrong export for useIsMounted hook

---

packages/common/src/hooks/useObjectTranslation.ts

Jira Ticket Reference : [MN-666](https://acvauctions.atlassian.net/browse/MN-666)
[MN-666]: https://acvauctions.atlassian.net/browse/MN-666?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fixed object translation not working properly when passing lng options

---

packages/network/src/api/inspection/mappers.ts
packages/network/src/api/models/pricingV2.ts
packages/network/src/api/models/task.ts
packages/network/test/api/inspection/data/apiAllInspectionsVerboseGet.data.json
packages/network/test/api/inspection/data/apiInspectionGet.data.json
packages/network/test/api/inspection/data/apiInspectionPost.data.json
packages/network/test/api/inspection/data/apiInspectionPost.data.ts
packages/types/src/api.ts

Jira Ticket Reference : [MN-652](https://acvauctions.atlassian.net/browse/MN-652)
Update the pricing V2 types to reflect methodology changes in API
[MN-652]: https://acvauctions.atlassian.net/browse/MN-652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update the pricing V2 types to reflect methodology changes in API

---

packages/network/src/api/inspection/mappers.ts
packages/network/test/api/inspection/data/apiInspectionGet.data.ts

Fixed missing vehicle ID in get inspection response

Fixed missing vehicle ID in get inspection response

---

packages/network/src/api/inspection/mappers.ts
packages/network/src/api/inspection/requests.ts
packages/network/test/api/inspection/mappers.test.ts
packages/network/test/api/inspection/requests.test.ts

Jira Ticket Reference : [MN-677](https://acvauctions.atlassian.net/browse/MN-677)
* Added `show_deleted` parameter to `getAllInpections` query function.
* Added `boolean` type to filters type
[MN-677]: https://acvauctions.atlassian.net/browse/MN-677?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Added show_deleted filter to getAllInspections function

---

packages/sights/research/data/all/all.json
packages/sights/research/schemas/subschemas/task.schema.json

Jira Ticket Reference : [MN-683](https://acvauctions.atlassian.net/browse/MN-683)
Changed tasks for "all" sights: damage_detection to compliances.
[MN-683]: https://acvauctions.atlassian.net/browse/MN-683?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Changed tasks for "all" sights: damage_detection to compliances.

---

apps/demo-app/src/components/AppRouter.tsx
apps/demo-app/src/pages/index.ts
packages/inspection-capture-web/src/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUDElementsSight/SightSlider/SightSlider.styles.ts
packages/inspection-capture-web/src/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUDTutorial/PhotoCaptureHUDTutorial.styles.ts
packages/inspection-capture-web/src/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUDTutorial/PhotoCaptureHUDTutorial.tsx
packages/inspection-capture-web/src/PhotoCapture/PhotoCaptureHUD/PhotoCaptureHUDTutorial/hooks.ts

Jira Ticket Reference : [MN-685](https://acvauctions.atlassian.net/browse/MN-685)
Improved responsiveness of the `PhotoCaptureTutorial` component to better support portrait orientation.
[MN-685]: https://acvauctions.atlassian.net/browse/MN-685?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fixed PhotoCapture tutorial portrait behavior

---

packages/network/src/api/image/requests.ts
packages/network/src/api/models/image.ts
packages/network/src/api/models/task.ts

Jira Ticket Reference : [MN-699](https://acvauctions.atlassian.net/browse/MN-699)
Fixed images_ocr task needs to be passed as a object: https://api.preview.monk.ai/v1/apidocs/#/Image/post_image_to_inspection
[MN-699]: https://acvauctions.atlassian.net/browse/MN-699?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fixed images_ocr passed as a task to addImage request

---

packages/inspection-capture-web/src/hooks/useTracking.ts
packages/inspection-capture-web/test/hooks/useTracking.test.ts
packages/posthog/package.json
yarn.lock

Jira Ticket Reference : [MN-595](https://acvauctions.atlassian.net/browse/MN-595)
[MN-595]: https://acvauctions.atlassian.net/browse/MN-595?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Go back to default distinct_id

---

apps/demo-app/src/local-config.json
packages/common-ui-web/src/components/Button/Button.styles.ts
packages/common-ui-web/src/components/InspectionGallery/InspectionGalleryItemCard/InspectionGalleryItemCard.styles.ts
packages/common-ui-web/src/components/VehicleTypeSelection/VehicleTypeSelectionCard/VehicleTypeSelectionCard.styles.ts

- **Font inheritance**: The font is now inherited from the parent element, enabling better customization and consistency across the application.  
- **Updated `thumbnailDomain`**: Changed to `"api.preview.monk.ai/image_resize"`.  

Font inherit from parent component

---

documentation/src/utils/schemas.ts
documentation/src/utils/schemas/createInspection.schema.ts
packages/inspection-capture-web/src/hooks/useUploadQueue.ts
packages/network/src/api/image/requests.ts
packages/network/src/api/inspection/mappers.ts
packages/network/src/api/models/image.ts
packages/network/src/api/models/task.ts
packages/network/test/api/image/requests.test.ts
packages/network/test/api/inspection/data/apiInspectionGet.data.ts
packages/sights/research/data/fesc20/fesc20.json
packages/sights/research/data/ff150/ff150.json
packages/sights/research/data/ffocus18/ffocus18.json
packages/sights/research/data/ftransit18/ftransit18.json
packages/sights/research/data/haccord/haccord.json
packages/sights/research/data/jgc21/jgc21.json
packages/sights/research/data/tsienna20/tsienna20.json
packages/sights/research/schemas/sight.schema.json
packages/sights/research/schemas/subschemas/wheelName.schema.json
packages/sights/src/build/buildJSONs.ts
packages/sights/test/build/buildJSON.test.ts
packages/types/src/api.ts
packages/types/src/sights.ts
packages/types/src/state/task.ts

Jira Ticket Reference : [MN-705](https://acvauctions.atlassian.net/browse/MN-705)
Added Close Up Wheel analysis Task. 
First version: Adds wheel_name is available (ignoring if it is a close up or long shot).
Next: Adds wheel_name will only be added if it's a close up shot.
[MN-705]: https://acvauctions.atlassian.net/browse/MN-705?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Added close ups in wheel analysis task

---

packages/inspection-capture-web/src/PhotoCapture/hooks/usePhotoCaptureSightState.ts

Jira Ticket Reference : [MN-711](https://acvauctions.atlassian.net/browse/MN-711)
[MN-711]: https://acvauctions.atlassian.net/browse/MN-711?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fixed tasksBySight

---

packages/sights/research/data/all/all.json

Fixed rear tire sights label inverted

---

packages/sights/research/data/all/all.json

Jira Ticket Reference : [MN-734](https://acvauctions.atlassian.net/browse/MN-734)
[MN-734]: https://acvauctions.atlassian.net/browse/MN-734?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Removed penny tests WA
